version: '3.5'

services:
  server:
    container_name: server
    build: .
    volumes:
      - .:/src
    ports:
      - "4000:4000"
    networks:
      - elastic
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/ 
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  # pg_admin:
  #   container_name: pg_admin
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: pgadmin@meltedspork.com 
  #     PGADMIN_DEFAULT_PASSWORD: postgres
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   ports:
  #     - "5000:80"
  #   networks:
  #     - postgres
  #   restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
      network.bind_host: 0.0.0.0
      network.host: 0.0.0.0
      discovery.type: single-node
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elastic

networks:
  postgres:
    driver: bridge
  elastic:
    driver: bridge
