version: '3.5'

services:
  server:
    container_name: server
    build: .
    volumes:
      - .:/src
    ports:
      - "4000:4000"
    networks:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-db:/var/lib/postgresql/data/ 
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  # pg_admin:
  #   container_name: pg_admin
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: pgadmin@meltedspork.com 
  #     PGADMIN_DEFAULT_PASSWORD: postgres
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   ports:
  #     - "3001:80"
  #   networks:
  #     - postgres
  #   restart: unless-stopped

networks:
  postgres:
    driver: bridge
